FROM --platform=$BUILDPLATFORM golang:1.26.2 AS builder

ARG TARGETOS=linux
ARG TARGETARCH=amd64
ARG VERSION=dev
ARG COMMIT=unknown
ARG BUILT_AT=unknown

WORKDIR /build

COPY go.mod go.sum Makefile ./
RUN make mod-download

COPY . .
RUN make build-agent \
    GOOS="${TARGETOS}" \
    GOARCH="${TARGETARCH}" \
    VERSION="${VERSION}" \
    COMMIT="${COMMIT}" \
    BUILT_AT="${BUILT_AT}"


FROM alpine:3.23

WORKDIR /app

COPY --from=builder /build/bin/agent /app/agent

CMD ["/app/agent"]