FROM golang:1.26.2 AS builder

ARG VERSION=dev
ARG COMMIT=unknown
ARG BUILT_AT=unknown

WORKDIR /build

COPY go.mod go.sum Makefile ./
RUN make mod-download

COPY . .
RUN make build-agent VERSION="${VERSION}" COMMIT="${COMMIT}" BUILT_AT="${BUILT_AT}"


FROM alpine:3.23

RUN adduser -D -g '' agent_user && \
    mkdir /app && \
    chown agent_user:agent_user /app

WORKDIR /app

COPY --from=builder --chown=agent_user:agent_user /build/bin/agent /app/agent

USER agent_user

CMD [ "/app/agent" ]
